export type CandidateFileRequest = { toolId: string; contentIdentity: string; path: string; offset: number };
export type CandidateFilePage = { path: string; offset: number; text: string; total: number; next: number; hasMore: boolean };
export type CandidateReviewRecord = { toolId: string; candidateContentIdentity: string; decision: "reviewed" | "rejected"; reviewIdentity: string; note: string; recordedAtUtc: string; sequence: number; recordSha256: string; previousRecordSha256?: string; reviewInterfaceVersion?: string; interaction?: string };
export type CandidateContract = { invocation: string; inputSchema: string; outputSchema: string };
export type BindingAction = "prepare" | "revoke" | "cleanup";
export type PreparedBindingRecord = { schemaVersion: number; toolId: string; candidateContentIdentity: string; reviewIdentity: string; reviewInterfaceVersion: string; reviewRecordSha256: string; state: "prepared-disabled" | "revoked" | "cleaned"; activationState: "disabled"; callableRoute: "none"; note: string; recordedAtUtc: string; sequence: number; previousRecordSha256: string; recordSha256: string };
export type BindingActionContext = { contentIdentity: string; reviewIdentity: string; currentRecordSha256?: string };
export type StageBindingContext = { contentIdentity: string; reviewIdentity: string; currentRecordSha256: string };
export type DisabledStageResult = { state: "staged-disabled"; currentRecordSha256: string; runtimeConfirmation: "Unknown" };
export type GeneratedToolActivationState = "disabled" | "active" | "revoked" | "stale";
export type GeneratedToolActivationFailureKind = "qualificationPending" | "unsupported" | "stale";
export type GeneratedToolActivationStatus = {
  attributedTo: "NeoBabylon.Host";
  toolId: string;
  activationAllowed: boolean;
  qualificationState: "pending" | "unsupported" | "qualified";
  failureKind: GeneratedToolActivationFailureKind | null;
  blockers: string[];
  callableTurnsAllowed: boolean | null;
  callableFailureKind: GeneratedToolActivationFailureKind | null;
  callableBlockers: string[];
  inventoryConfirmation: number | string | null;
  state: GeneratedToolActivationState;
  contentIdentity: string | null;
  reviewIdentity: string | null;
  bindingRecordSha256: string | null;
  activationRecordSha256: string | null;
  hostQualificationIdentity: string | null;
  record: GeneratedToolActivationHistoryRecord | null;
  requestedAuthority: Record<string, unknown> | null;
};
export type GeneratedToolActivationHistoryRecord = {
  schemaVersion: number;
  toolId: string;
  sequence: number;
  event: "denied" | "activated" | "revoked";
  state: "disabled" | "active" | "revoked";
  candidateContentIdentity: string | null;
  reviewIdentity: string | null;
  reviewRecordSha256: string | null;
  reviewSnapshotIdentity: string | null;
  bindingRecordSha256: string | null;
  invocationPlanIdentity: string | null;
  nodeRuntimeSha256: string | null;
  inputSchemaSha256: string | null;
  outputSchemaSha256: string | null;
  dependencyIdentity: string | null;
  authorityIdentity: string | null;
  hostQualificationIdentity: string | null;
  activationRecordSha256: string | null;
  qualificationState: "pending" | "unsupported" | "qualified";
  failureKind: GeneratedToolActivationFailureKind | null;
  blockers: string[];
  requestedAuthority: Record<string, unknown> | null;
  note: string;
  recordedAtUtc: string;
  previousRecordSha256: string;
  recordSha256: string;
};
export type GeneratedToolReviewComparison = {
  attributedTo: "NeoBabylon.Host";
  toolId: string;
  comparisonState: "available" | "unavailable" | "noPriorReview";
  unavailableReason: string | null;
  failureKind: string | null;
  priorDecision: "reviewed" | "rejected" | null;
  priorReviewIdentity: string | null;
  reviewedContentIdentity: string | null;
  currentContentIdentity: string;
  addedFiles: GeneratedToolReviewFileChange[];
  removedFiles: GeneratedToolReviewFileChange[];
  modifiedFiles: GeneratedToolReviewFileChange[];
  changedManifestFields: Array<{ field: string; beforeJson: string; afterJson: string }>;
  reviewedEvidence: GeneratedToolReviewEvidence[];
  currentEvidence: GeneratedToolReviewEvidence[];
};
export type GeneratedToolReviewFileChange = {
  path: string;
  previousSha256: string;
  currentSha256: string | null;
  beforePreview: string | null;
  afterPreview: string | null;
  beforePreviewTruncated: boolean;
  afterPreviewTruncated: boolean;
  previewAvailable: boolean;
};
export type GeneratedToolReviewEvidence = {
  kind: string;
  evidenceId: string;
  outcome: string;
  description: string;
  path: string;
  sha256: string;
};
export type GeneratedToolActivationTransition = {
  attributedTo: "NeoBabylon.Host";
  failureKind: GeneratedToolActivationFailureKind | null;
  status: GeneratedToolActivationStatus;
  record: GeneratedToolActivationHistoryRecord | null;
};

export function candidateContract(candidate: unknown): CandidateContract | null;
export function createSerialRequestQueue(): <T>(request: () => Promise<T>) => Promise<T>;
export function parseCandidateFilePage(response: unknown, request: CandidateFileRequest): CandidateFilePage;
export function parseReviewHistory(response: unknown, toolId: string): CandidateReviewRecord[];
export function currentReviewRecord(history: CandidateReviewRecord[], contentIdentity: string): CandidateReviewRecord | null;
export function reviewNoteError(note: string): string | null;
export function parsePreparedBindingHistory(response: unknown, toolId: string): PreparedBindingRecord[];
export function parsePreparedBindingToolIds(response: unknown): string[];
export function bindingActionContext(action: BindingAction, currentReview: CandidateReviewRecord | null, history: PreparedBindingRecord[] | null, contentIdentity: string): BindingActionContext | null;
export function stageBindingContext(currentReview: CandidateReviewRecord | null, history: PreparedBindingRecord[] | null, contentIdentity: string): StageBindingContext | null;
export function confirmDisabledStageResponse(response: unknown, toolId: string, context: StageBindingContext): DisabledStageResult;
export function verifyStageRecovery(listing: unknown, reviews: unknown, bindings: unknown, target: StageBindingContext & { toolId: string }): { reviewHistory: CandidateReviewRecord[]; bindingHistory: PreparedBindingRecord[] };
export function confirmBindingTransition(response: unknown, history: PreparedBindingRecord[] | null, action: BindingAction, toolId: string, context: BindingActionContext, previous: PreparedBindingRecord | null): PreparedBindingRecord;
export function parseGeneratedToolActivationStatus(response: unknown, toolId: string): GeneratedToolActivationStatus;
export function parseGeneratedToolActivationHistory(response: unknown, toolId: string): GeneratedToolActivationHistoryRecord[];
export function parseGeneratedToolActivationTransition(response: unknown, toolId: string, expectedState?: GeneratedToolActivationState): GeneratedToolActivationTransition;
export function parseGeneratedToolReviewComparison(response: unknown, toolId: string, contentIdentity: string): GeneratedToolReviewComparison;
