<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>WorkspaceConsolidationInventory</AssemblyName>
    <RootNamespace>NeoBabylon.WorkspaceConsolidationInventory</RootNamespace>
  </PropertyGroup>
</Project>
